-- init (up)
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,

  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,

  created_at DATETIME NOT NULL DEFAULT NOW(),
  soft_deleted BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS migrations (
  id INT AUTO_INCREMENT PRIMARY KEY,

  name VARCHAR(255) UNIQUE NOT NULL,
  applied_at DATETIME NOT NULL,
  batch INT NOT NULL
);